import React, { createContext } from 'react';

export default createContext({
    image: [],
    setImage: () => { },
    imagePath: '',
    setImagePath: () => { },
    showModalConfirm: '',
    setShowModalConfirm: () => { },
    showModalSimpleMessage: '',
    setShowModalSimpleMessage: () => { },
    showModalCroppeImage: '',
    setShowModalCroppeImage: () => { },
    showModalInput: '',
    setShowModalInput: () => { },
    messageModal: '',
    setMessageModal: () => { },
    sender: '',
    setSender: () => { },
    inputTextModify: '',
    setInputTextModify: () => { },
    textButtonConfirm: '',
    setTextButtonConfirm: () => { },
    imageModal: '',
    setImageModal: () => { },
    selectedColor: '',
    setSelectedColor: () => { },
    listCollections: '',
    setListCollections: () => { },
    listCategories: '',
    setListCategories: () => { },
    is_Edit: '',
    setIs_Edit: () => { },
    categoriesChecked: '',
    setCategoriesChecked: () => { },
    searchValue: '',
    setSearchValue: () => { },
    isDirty: '',
    setIsDirty: () => { },
    tmp_parameter: '',
    setTmp_parameter: () => { },
    deleteThisCategory: '',
    setDeleteThisCategory: () => { },
    handleModalConfirm: () => { },
    handleModalCancel: () => { },
    nameCollection: '',
    setNameCollection: () => { },
    descriptionCollection: '',
    setDescriptionCollection: () => { },
    descriptionCollectionForMeta: '',
    setDescriptionCollectionForMeta: () => { },
    conditions: '',
    setConditions: () => { },
    isAutoConditions: '',
    setIsAutoConditions: () => { },
    allConditionsNeeded: '',
    setAllConditionsNeeded: () => { },
    notIncludePrevProduct: '',
    setNotIncludePrevProduct: () => { },
    warningIdCondition: '',
    setWarningIdCondition: () => { },
    normalizUrl: () => { },
    metaTitle: '',
    setMetaTitle: () => { },
    metaDescription: '',
    setMetaDescription: () => { },
    metaUrl: '',
    setMetaUrl: () => { },
    imageName: '',
    setImageName: () => { },
    alt: '',
    setAlt: () => { },
    categoryName: '',
    setCategoryName: () => { },
    categoryId: '',
    setCategoryId: () => { },
    dateField: '',
    setDateField: () => { },
    tinyLanguage: '',
    setTinyLanguage: () => { },
    idCollection: '',
    setIdCollection: () => { },
    initCollectionForm: () => { },
    cleanTemporayStorage: '',
    is: '',
    setIs: () => { },
    collectionForm: '',
    setCollectionForm: () => { },
    deleteThisCollection: '',
    setDeleteThisCollection: () => { },
    wrapIndexcroppe: '',
    setWrapIndexcroppe: () => { },
    listCollectionsChecked: '',
    setListCollectionsChecked: () => { },
    listCollectionsFiltered: '',
    setListCollectionsFiltered: () => { },
    showModalListOperations: '',
    setShowModalListOperations: () => { },
    typeOperationListCollections: '',
    setTypeOperationListCollections: () => { },
    senderCancel: '',
    setSenderCancel: () => { },
    showModalConfirmOperations: '',
    setShowModalConfirmOperations: () => { },
    messageArray: '',
    setMessageArray: () => { },
    notThisId: '',
    setNotThisId: () => { },
    dsablNamProd: '',
    setDsablNamProd: () => { },
    dsablType: '',
    setDsablType: () => { },
    dsablSuppl: '',
    setDsablSuppl: () => { },
    dsablPrice: '',
    setDsablPrice: () => { },
    dsablTag: '',
    setDsablTag: () => { },
    dsablBeforePromo: '',
    setDsablBeforePromo: () => { },
    dsablWeight: '',
    setDsablWeight: () => { },
    dsablStock: '',
    setDsablStock: () => { },
    dsablDate: '',
    setDsablDate: () => { },
    refresh: '',
    setRefresh: () => { },
    nameSupplier: '',
    setNameSupplier: () => { },
    emailSupplier: '',
    setEmailSupplier: () => { },
    phoneSupplier: '',
    setPhoneSupplier: () => { },
    webSiteSupplier: '',
    setWebSiteSupplier: () => { },
    adressSupplier: '',
    setAdressSupplier: () => { },
    citySupplier: '',
    setCitySupplier: () => { },
    countrySupplier: '',
    setCountrySupplier: () => { },
    listSuppliers: '',
    setListSuppliers: () => { },
    initSupplierForm: () => { },
    imageVariantes: [],
    setImageVariantes: () => { },
    checkedVariantesList: [],
    setCheckedVariantesList: () => { },
    selectedVariantesList: [],
    setSelectedVariantesList: () => { },
    allOptionsVariantesNeeded: '',
    setAllOptionsVariantesNeeded: () => { },
    isHideDeletedVariantes: '',
    setIsHideDeletedVariantes: () => { },
    variante: {},
    setVariante: () => { },
    listType: '',
    setListType: () => { },
    optionsData: '',
    setOptionsData: () => { },
    activeCalculTva: '',
    setActiveCalculTva: () => { },
    tvaRateList: '',
    setTvaRateList: () => { },
    listTransporters: '',
    setListTransporters: () => { },
    screenSize: '',
    isInAutoCollection: '',
    setIsInAutoCollection: () => { },
    showSideNav: '',
    setShowSideNav: () => { },
    products: [],
    setProducts: () => { },
    listProductsFiltered: [], 
    setListProductsFiltered: () => { },
    listProductsChecked: [],  
    setListProductsChecked: () => { },
    listCollectionNames: '', 
    setListCollectionNames: () => { },
    isEditProduct: '', 
    setIsEditProduct: () => { },
    showInitButton: '', 
    setShowInitButton: () => { },
    imageHasBeenChanged: '', 
    setImageHasBeenChanged: () => { },
    showOptions: '', 
    setShowOptions: () => { },
    IdProduct: '',  
    setIdProduct: () => { },
    initCreateProduct: () => { },
    tvaComparation: '', 
    setTvaComparation: () => { },
    isDirtyCreateProduct: '', 
    setIsDirtyCreateProduct: () => { },
    checkIfCreateProductIsDirty: () => { },
    hooksComparation: '', 
    setHooksComparation: () => { },
    hasLeaveThisPage: '', 
    setHasLeaveThisPage: () => { },
    isVisible: '',  
    setIsVisible: () => { },
    handleLocalStorageProduct: () => { },
    productForm: '',
    setProductForm: () => { },
    handleLocalStorageCollection: () => { },

    
});
