import React, { createContext } from 'react';

export default createContext({
    image: [],
    setImage: () => { },
    imagePath: '',
    setImagePath: () => { },
    showModalConfirm: '',
    setShowModalConfirm: () => { },
    showModalSimpleMessage: '',
    setShowModalSimpleMessage: () => { },
    showModalCroppeImage: '',
    setShowModalCroppeImage: () => { },
    showModalInput: '',
    setShowModalInput: () => { },
    messageModal: '',
    setMessageModal: () => { },
    sender: '',
    setSender: () => { },
    inputTextModify: '',
    setInputTextModify: () => { },
    textButtonConfirm: '',
    setTextButtonConfirm: () => { },
    imageModal: '',
    setImageModal: () => { },
    selectedColor: '',
    setSelectedColor: () => { },
    listCollections: '',
    setListCollections: () => { },
    listCategories: '',
    setListCategories: () => { },
    is_Edit: '',
    setIs_Edit: () => { },
    categoriesChecked: '',
    setCategoriesChecked: () => { },
    searchValue: '',
    setSearchValue: () => { },
    isDirty: '',
    setIsDirty: () => { },
    tmp_parameter: '',
    setTmp_parameter: () => { },
    deleteThisCategory: '',
    setDeleteThisCategory: () => { },
    handleModalConfirm: () => { },
    handleModalCancel: () => { },
    nameCollection: '',
    setNameCollection: () => { },
    descriptionCollection: '',
    setDescriptionCollection: () => { },
    descriptionCollectionForMeta: '',
    setDescriptionCollectionForMeta: () => { },
    conditions: '',
    setConditions: () => { },
    isAutoConditions: '',
    setIsAutoConditions: () => { },
    allConditionsNeeded: '',
    setAllConditionsNeeded: () => { },
    notIncludePrevProduct: '',
    setNotIncludePrevProduct: () => { },
    warningIdCondition: '',
    setWarningIdCondition: () => { },
    normalizUrl: () => { },
    metaTitle: '',
    setMetaTitle: () => { },
    metaDescription: '',
    setMetaDescription: () => { },
    metaUrl: '',
    setMetaUrl: () => { },
    imageName: '',
    setImageName: () => { },
    alt: '',
    setAlt: () => { },
    categoryName: '',
    setCategoryName: () => { },
    categoryId: '',
    setCategoryId: () => { },
    dateField: '',
    setDateField: () => { },
    tinyLanguage: '',
    setTinyLanguage: () => { },
    idCollection: '',
    setIdCollection: () => { },
    initCollectionForm: () => { },
    cleanTemporayStorage: '',
    is: '',
    setIs: () => { },
    collectionForm: '',
    setCollectionForm: () => { },
    deleteThisCollection: '',
    setDeleteThisCollection: () => { },
    wrapIndexcroppe: '',
    setWrapIndexcroppe: () => { },
    listCollectionsChecked: '',
    setListCollectionsChecked: () => { },
    listCollectionsFiltered: '',
    setListCollectionsFiltered: () => { },
    showModalListOperations: '',
    setShowModalListOperations: () => { },
    typeOperationListCollections: '',
    setTypeOperationListCollections: () => { },
    senderCancel: '',
    setSenderCancel: () => { },
    showModalConfirmOperations: '',
    setShowModalConfirmOperations: () => { },
    messageArray: '',
    setMessageArray: () => { },
    notThisId: '',
    setNotThisId: () => { },
    dsablNamProd: '',
    setDsablNamProd: () => { },
    dsablType: '',
    setDsablType: () => { },
    dsablSuppl: '',
    setDsablSuppl: () => { },
    dsablPrice: '',
    setDsablPrice: () => { },
    dsablTag: '',
    setDsablTag: () => { },
    dsablBeforePromo: '',
    setDsablBeforePromo: () => { },
    dsablWeight: '',
    setDsablWeight: () => { },
    dsablStock: '',
    setDsablStock: () => { },
    dsablDate: '',
    setDsablDate: () => { },
    refresh: '',
    setRefresh: () => { },
    nameProduct: '',
    setNameProduct: () => { },
    ribbonProduct: '',
    setRibbonProduct: () => { },
    descriptionProduct: '',
    setDescriptionProduct: () => { },
    nameSupplier: '',
    setNameSupplier: () => { },
    emailSupplier: '',
    setEmailSupplier: () => { },
    phoneSupplier: '',
    setPhoneSupplier: () => { },
    webSiteSupplier: '',
    setWebSiteSupplier: () => { },
    adressSupplier: '',
    setAdressSupplier: () => { },
    citySupplier: '',
    setCitySupplier: () => { },
    countrySupplier: '',
    setCountrySupplier: () => { },
    listSuppliers: '',
    setListSuppliers: () => { },
    supplier: '',
    setSupplier: () => { },
    initSupplierForm: () => { },
    collections: '',
    setCollections: () => { },
    productPrice: '',
    setProductPrice: () => { },
    promoApplied: '',
    setPromoApplied: () => { },
    promoType: '',  
    setPromoType: () => { },
    reducedProductPrice: '',
    setReducedProductPrice: () => { },
    productCost: '',
    setProductCost: () => { },
    productStock: '',
    setProductStock: () => { },
    optionsObj: [],
    setOptionsObj: () => { },
    unlimited: [],
    setUnlimited: () => { },
    imageVariantes: [],
    setImageVariantes: () => { },
    variantes: [],
    setVariantes: () => { },
    checkedVariantesList: [],
    setCheckedVariantesList: () => { },
    selectedVariantesList: [],
    setSelectedVariantesList: () => { },
    allOptionsVariantesNeeded: '',
    setAllOptionsVariantesNeeded: () => { },
    isHideDeletedVariantes: '',
    setIsHideDeletedVariantes: () => { },
    variante: {},
    setVariante: () => { },
    listType: '',
    setListType: () => { },
    optionsData: '',
    setOptionsData: () => { },
    changedVariantes: '',
    setChangedVariantes: () => { },
    productCode: '',
    setProductCode: () => { },
    activeCalculTva: '',
    setActiveCalculTva: () => { },
    tvaRateList: '',
    setTvaRateList: () => { },
    tva: '',
    setTva: () => { },
    metaTitleProduct: '',
    setMetaTitleProduct: () => { },
    metaDescriptionProduct: '',
    setMetaDescriptionProduct: () => { },
    metaUrlProduct: '',
    setMetaUrlProduct: () => { },
    listTransporters: '',
    setListTransporters: () => { },
    transporter: '',
    setTransporter: () => { },
    productParcelWeight: '',
    setProductParcelWeight: () => { },
    productParcelWeightMeasureUnit: '',
    setProductParcelWeightMeasureUnit: () => { },
    screenSize: '',
    isInAutoCollection: '',
    setIsInAutoCollection: () => { },
    showSideNav: '',
    setShowSideNav: () => { },
    products: [],
    setProducts: () => { },
    listProductsFiltered: [], 
    setListProductsFiltered: () => { },
    listProductsChecked: [],  
    setListProductsChecked: () => { },
    dateFieldProduct: '', 
    setDateFieldProduct: () => { },
    listCollectionNames: '', 
    setListCollectionNames: () => { },
    isEditProduct: '', 
    setIsEditProduct: () => { },
    isShowPromoProduct: '',  
    setIsShowPromoProduct: () => { },
    showInitButton: '', 
    setShowInitButton: () => { },
    imageHasBeenChanged: '', 
    setImageHasBeenChanged: () => { },


});
